CorseUILayer/Controllers/ClassScheduleController.cs
using BusinessLayer.Concrete;
using CorseEntity.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Drawing.Printing;

namespace CorseUILayer.Controllers
{
    [Authorize]
    public class ClassScheduleController : Controller
    {
        ClassScheduleManager CSM = new ClassScheduleManager(new EfClassScheduleRepository());

        [HttpGet]
        public IActionResult Index(int id)
        {
            var result = CSM.GetAllIdScheduleList(id);
            return View(result);
         }
    
        public IActionResult ScheduleDelete(int id) 
        {
            var result = CSM.GetByIdSchedule(id);
            CSM.DeleteSchedule(id);
            return Redirect("/ClassSchedule/Index/" + result.GroupId);
        }

        [HttpGet]
        public IActionResult GetUpdateSchedule(int id) 
        {
            var result1 = CSM.ScheduleChooseList();
            ViewBag.Values = result1;
            var result = CSM.GetByIdSchedule(id);
            return View("GetUpdateSchedule", result);
        }

        [HttpPost]
        public IActionResult UpdateSchedule(Schedule schedule)
        {
            CSM.UpdateSchedule(schedule);
            return Redirect("/ClassSchedule/Index/" + schedule.GroupId);
        }

        [HttpGet]
        public IActionResult GetAddSchedule() 
        {
            var result1 = CSM.ScheduleChooseList();
            ViewBag.Values = result1;
            return View();
        }

        [HttpPost]
        public IActionResult AddSchedule(Schedule schedule)
        {
            CSM.AddSchedule(schedule);
            return Redirect("/ClassSchedule/Index/"+schedule.GroupId);
        }




    }
}

CorseUILayer/Views/ClassSchedule/GetAddSchedule.cshtml
@model CorseEntity.Concrete.Schedule
@{
    ViewData["Title"] = "GetAddSchedule";
    Layout = "~/Views/Shared/_Layout_Corse.cshtml";
}
@using (Html.BeginForm("AddSchedule", "ClassSchedule", FormMethod.Post))
{
   
    <br />
    <b>Bazar ertəsi</b>
    @Html.TextBoxFor(x => x.Monday, new { @class = "form-control" })

    <br />
    <b>Çərşənbə axşamı</b>
    @Html.TextBoxFor(x => x.Tuesday, new { @class = "form-control" })

    <br />
    <b>Çərşənbə</b>
    @Html.TextBoxFor(x => x.Wednesday, new { @class = "form-control" })

    <br />
    <b>Cümə axşamı</b>
    @Html.TextBoxFor(x => x.Thursday, new { @class = "form-control" })

    <br />
    <b>Cümə</b>
    @Html.TextBoxFor(x => x.Friday, new { @class = "form-control" })

    <br />
    <b>Şənbə</b>
    @Html.TextBoxFor(x => x.Saturday, new { @class = "form-control" })

    <br />
    <b>Bazar</b>
    @Html.TextBoxFor(x => x.Sunday, new { @class = "form-control" })

    <br />
    <b>Tarix</b>
    @Html.TextBoxFor(x => x.CreateTime, new { @class = "form-control" })

    <br />
    <b>Qrup id</b>
    @Html.DropDownListFor(x=>x.GroupId,(List<SelectListItem>)ViewBag.Values,new {@class="form-control"})

    <br />
    <button class="btn btn-info"> Elave et </button>

}

CorseUILayer/Views/ClassSchedule/GetUpdateSchedule.cshtml
@model CorseEntity.Concrete.Schedule
@{
    ViewData["Title"] = "GetUpdateSchedule";
    Layout = "~/Views/Shared/_Layout_Corse.cshtml";
}

@using (Html.BeginForm("UpdateSchedule", "ClassSchedule", FormMethod.Post))
{
    <br />
    <br />
    <b>ID</b>
    @Html.TextBoxFor(x => x.ClassScheduleId, new { @class = "form-control" })
    

    <br />
    <b>Bazar ertəsi</b>
    @Html.TextBoxFor(x => x.Monday, new { @class = "form-control" })

    <br />
    <b>Çərşənbə axşamı</b>
    @Html.TextBoxFor(x => x.Tuesday, new { @class = "form-control" })

    <br />
    <b>Çərşənbə</b>
    @Html.TextBoxFor(x => x.Wednesday, new { @class = "form-control" })

    <br />
    <b>Cümə axşamı</b>
    @Html.TextBoxFor(x => x.Thursday, new { @class = "form-control" })

    <br />
    <b>Cümə</b>
    @Html.TextBoxFor(x => x.Friday, new { @class = "form-control" })

    <br />
    <b>Şənbə</b>
    @Html.TextBoxFor(x => x.Saturday, new { @class = "form-control" })

    <br />
    <b>Bazar</b>
    @Html.TextBoxFor(x => x.Sunday, new { @class = "form-control" })

    <br />
    <b>Tarix</b>
    @Html.TextBoxFor(x => x.CreateTime, new { @class = "form-control" })

    <br />
    <b>Qrup id</b>
    @Html.DropDownListFor(x=>x.GroupId,(List<SelectListItem>)ViewBag.Values,new {@class="form-control"})

    <br />
    <button class="btn btn-info"> Guncelle </button>

}

CorseUILayer/Views/ClassSchedule/Index.cshtml
@model List<CorseEntity.Concrete.Schedule>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout_Corse.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Bazar ertəsi</th>
        <th>Çərşənbə axşamı</th>
        <th>Çərşənbə</th>
        <th>Cümə axşamı</th>
        <th>Cümə</th>
        <th>Şənbə</th>
        <th>Bazar</th>
        <th>Yaradilma tarixi</th>
        <th>Guncelle</th>
        <th>Sil</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ClassScheduleId</td>
            <td>@item.Monday</td>
            <td>@item.Tuesday</td>
            <td>@item.Wednesday</td>
            <td>@item.Thursday</td>
            <td>@item.Friday</td>
            <td>@item.Saturday</td>
            <td>@item.Sunday</td>
            <td>@item.CreateTime.ToString("dd/MM/yyyy") </td>
            <td><a href="/ClassSchedule/GetUpdateSchedule/@item.ClassScheduleId/" class="btn btn-warning">Guncelle</a></td>
            <td><a href="/ClassSchedule/ScheduleDelete/@item.ClassScheduleId/" class="btn btn-danger">Sil</a></td>
        </tr>
    }
</table>
<a href="/ClassSchedule/GetAddSchedule/" class="btn btn-primary">Yeni cedvel</a>