CorseUILayer/Controllers/GroupController.cs
using BusinessLayer.Concrete;
using CorseEntity.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.RegularExpressions;

namespace CorseUILayer.Controllers
{
   [Authorize]
    public class GroupController : Controller
    {
        GroupManager gm = new GroupManager(new EfGroupRepository());
        LanguageManager la = new LanguageManager(new EfLanguageRepository());

        [HttpGet]
        public IActionResult Index(int id)
        {
           
            var result = gm.GetAllIdGroupList(id);
            return View(result);
        }
        [HttpGet]
        public IActionResult GetUpdateGroup(int id)
        {
            var resultT = gm.TeacherChooseList();
            ViewBag.Values2 = resultT;
            var resultG = gm.GroupChooseList();
            ViewBag.Values = resultG;
            var result = gm.GetByIdGroup(id);
            /*ViewBag.languageId = result.LanguageAboutId;
            ViewBag.LanguageAbout = la.GetByIdLanguage(ViewBag.languageId);*/
            

        return View("GetUpdateGroup", result);
        }

        [HttpPost]
        public IActionResult GroupUpdate(GroupAbout group)
        {          
            gm.UpdateGroup(group); 
            return Redirect("/Group/Index/"+group.LanguageAboutId);
        }

        public IActionResult DeleteGroup(int id)
        {
          var result = gm.GetByIdGroup(id);
            gm.ChangeGroup(result);
            return Redirect("/Group/Index/" + result.LanguageAboutId);
        }

        [HttpGet]
        public IActionResult GetAddGroup()
        {
            var resultT = gm.TeacherChooseList();
            ViewBag.Values2 = resultT;
            var result1 = gm.GroupChooseList();
            ViewBag.Values = result1;

            return View();
        }

        [HttpPost]
        public IActionResult GroupAdd(GroupAbout group)
        {
            gm.AddGroup(group);
            return Redirect("/Group/Index/" + group.LanguageAboutId);
        }
        
    }
}

CorseUILayer/Views/Group/GetAddGroup.cshtml
@model CorseEntity.Concrete.GroupAbout
@{
    ViewData["Title"] = "GetAddGroup";
    Layout = "~/Views/Shared/_Layout_Corse.cshtml";
}

@using (Html.BeginForm("GroupAdd", "Group", FormMethod.Post))
{
    <br />

    <b>Idsi</b>
    @Html.TextBoxFor(x => x.GroupId, new { @class = "form-control" })

    <br />
    <b>Qrupun adi</b>
    @Html.TextBoxFor(x => x.GroupName, new { @class = "form-control" })
  
    <br />
    <b>Kursun adi</b>
    @Html.DropDownListFor(x=>x.LanguageAboutId,(List<SelectListItem>)ViewBag.Values,new {@class="form-control"})

    <br />
    <b>Muellim</b>
    @Html.DropDownListFor(x=>x.TeacherId,(List<SelectListItem>)ViewBag.Values2,new {@class="form-control"})

    <br />
    <button class="btn btn-info"> Elave et </button>

}

CorseUILayer/Views/Group/GetUpdateGroup.cshtml
@model CorseEntity.Concrete.GroupAbout
@{
    ViewData["Title"] = "GetUpdateGroup";
    Layout = "~/Views/Shared/_Layout_Corse.cshtml";
}

@using (Html.BeginForm("GroupUpdate", "Group", FormMethod.Post))
{
    <br />

    <b>Idsi</b>
    @Html.TextBoxFor(x => x.GroupId, new { @class = "form-control" })

    <br />
    <b>Qrupun adi</b>
    @Html.TextBoxFor(x => x.GroupName, new { @class = "form-control" })

    <br />
    <b>Kurs</b>
    @Html.DropDownListFor(x=>x.LanguageAboutId,(List<SelectListItem>)ViewBag.Values,new {@class="form-control"})
 
        @* <select class="form-control" >
       @foreach (var value in ViewBag.Values)
        {
            
            if (value.Value == ViewBag.languageId.ToString())
            {
                <option selected id="value.Value">@value.Text</option>
            }
            else
            {
                <option id="value.Value">@value.Text</option>
            }
        }    
    </select>*@

    <br />
    <b>Muellim</b>
    @Html.DropDownListFor(x=>x.TeacherId,(List<SelectListItem>)ViewBag.Values2,new {@class="form-control"})

    <br />
    <button class="btn btn-info"> Guncelle </button>

}

CorseUILayer/Views/Group/Index.cshtml
@using CorseEntity.Concrete
@model List<GroupAbout>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout_Corse.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>Idsi</th>
        <th>Qrupun adi</th>
        <th>Yaranma tarixi</th>
        <th>Telebeler</th>
        <th>Ders cedveli</th>
        <th>Guncelle</th>
        <th>Sil</th>
    </tr>
 
        @foreach(var item in Model)
        {
        <tr>
            <td>@item.GroupId</td>
            <td>@item.GroupName</td>
            <td>@item.CreateTime.ToString("dd/MM/yyyy")</td>
            <td><a href="/Student/Index/@item.GroupId/" class="btn btn-primary">Telebeler</a></td>
            <td><a href="/ClassSchedule/Index/@item.GroupId/" class="btn btn-primary">Ders cedveli</a></td>
            <td><a href="/Group/GetUpdateGroup/@item.GroupId/" class="btn btn-warning">Guncelle</a></td>
            <td><a href="/Group/DeleteGroup/@item.GroupId/" class="btn btn-danger">Sil</a></td>
        </tr>
        }
    
</table>

<a href="/Group/GetAddGroup/" class="btn btn-primary">Yeni qrup</a>