CorseUILayer/Controllers/ExamController.cs
using BusinessLayer.Concrete;
using CorseEntity.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Mvc;

namespace CorseUILayer.Controllers
{
    public class ExamController : Controller
    {
        ExamManager Em = new ExamManager(new EfExamRepository());

        [HttpGet]
        public IActionResult Index(int id)
        {
            var result1 = Em.GetListStudentNameExam(id);
            ViewBag.StudentName = result1;
           var result = Em.GetByIdExamAll(id);
            return View(result);
        }

        [HttpGet]
        public IActionResult GetAddExam()
        {
            var result1 = Em.ExamChooseList();
            ViewBag.Values = result1;
            return View();
        
        }

        [HttpPost]
        public IActionResult ExamAdd(Exam exam) 
        {
            Em.AddExam(exam);
            return Redirect("/Exam/Index/" + exam.StudentID);

        }

        [HttpGet]
        public IActionResult GetUpdateExam(int id)
        {
            var result1 = Em.ExamChooseList();
            ViewBag.Values = result1;
            var result = Em.GetByIdExam(id);
            return View("GetUpdateExam",result);
        }

        [HttpPost]
        public IActionResult UpdateExam(Exam exam)
        {
             Em.UpdateExam(exam);
            return Redirect("/Exam/Index/" + exam.StudentID);
        }
     
        public IActionResult ExamDelete(int id)
        {
            Em.DeleteExam(id);
            var result = Em.GetByIdExam(id);
            return Redirect("/Exam/Index/" + result.StudentID);
        }
       

    }
}

CorseUILayer/Views/Exam/GetAddExam.cshtml
@model CorseEntity.Concrete.Exam
@{
    ViewData["Title"] = "GetAddExam";
    Layout = "~/Views/Shared/_Layout_Corse.cshtml";
}

@using (Html.BeginForm("ExamAdd", "Exam", FormMethod.Post))
{
    <br />

    <b>Idsi</b>
    @Html.TextBoxFor(x => x.ExamId, new { @class = "form-control" })

    <br />
    <b>Imtahan movzusu</b>
    @Html.TextBoxFor(x => x.ExamTopic, new { @class = "form-control" })

    <br />
    <b>100 uzerinden qiymeti</b>
    @Html.TextBoxFor(x => x.ExamGrade, new { @class = "form-control" })

   @* <br />
    <b>Tarix</b>
    @Html.TextBoxFor(x => x.ExamTime, new { @class = "form-control" })*@

    <br />
    <b>Telebe adi</b>
    @Html.DropDownListFor(x=>x.StudentID,(List<SelectListItem>)ViewBag.Values,new {@class="form-control"})

    <br />
    <button class="btn btn-info"> Elave et </button>

}

CorseUILayer/Views/Exam/GetUpdateExam.cshtml
@model CorseEntity.Concrete.Exam
@{
    ViewData["Title"] = "GetUpdateExam";
    Layout = "~/Views/Shared/_Layout_Corse.cshtml";
}

@using (Html.BeginForm("UpdateExam", "Exam", FormMethod.Post))
{
    <br />

    <b>Id</b>
    @Html.TextBoxFor(x => x.ExamId, new { @class = "form-control" })

    <br />
    <b>Qrupun adi</b>
    @Html.TextBoxFor(x => x.ExamTopic, new { @class = "form-control" })

    <br />
    <b>100 uzerinden qiymeti</b>
    @Html.TextBoxFor(x => x.ExamGrade, new { @class = "form-control" })

  @*  <br />
    <b>Imtahan tarixi</b>
    @Html.TextBoxFor(x => x.ExamTime, new { @class = "form-control" })
*@
    <br />
    <b>Telebe adi</b>
    @Html.DropDownListFor(x=>x.StudentID,(List<SelectListItem>)ViewBag.Values,new {@class="form-control"})



    <br />
    <button class="btn btn-info"> Guncelle </button>

}

CorseUILayer/Views/Exam/Index.cshtml
@model List<CorseEntity.Concrete.Exam>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout_Corse.cshtml";
}


<table class="table table-bordered">
    <tr>
        <th>Idsi</th>
        <th>Telebe adi</th>
        <th>Imtahan movzusu</th>
        <th>100 uzerinden qiymetlendirme</th>
        <th>Tarixi</th>
       
        <th>Guncelle</th>
        <th>Sil</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ExamId</td>
          @*  <td>@ViewBag.StudentName</td>*@
            <td>@(ViewBag.StudentName.Count > 0 ? ViewBag.StudentName[0] : "Not Available")</td>

            <td>@item.ExamTopic</td>
            <td>@item.ExamGrade</td>
            <td>@item.ExamTime.ToString("dd/MM/yyyy")</td>
            <td><a href="/Exam/GetUpdateExam/@item.ExamId/" class="btn btn-warning">Guncelle</a></td>
            <td><a href="/Exam/ExamDelete/@item.ExamId/" class="btn btn-danger">Sil</a></td>
        </tr>
    }

</table>

<a href="/Exam/GetAddExam/" class="btn btn-primary">Yeni imtahan</a>