CorseUILayer/Controllers/EvaluationController.cs
using BusinessLayer.Concrete;
using CorseEntity.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.DependencyResolver;

namespace CorseUILayer.Controllers
{
    [Authorize]
    public class EvaluationController : Controller
    {
        EvaluationManager EM = new EvaluationManager(new EfEvaluationRepository());


        [HttpGet]
        public IActionResult Index(int id)
        {
            var result1 = EM.GetListStudentNameEvaluation(id);
            ViewBag.StudentName = result1;
            var result = EM.GetIdEvaluationList(id);
            return View(result);
        }

        [HttpGet]
        public IActionResult GetEvaluation()
        {
            var result1 = EM.EvaluationChooseList();
            ViewBag.Values = result1;
            return View();               
        }

        [HttpPost]
        public IActionResult GetAddEvaluation(Evaluation evaluation,int id)
        {
           
            EM.AddEvaluation(evaluation,id);

            return Redirect("/Evaluation/Index/" + evaluation.StudentID);
        }

        [HttpGet]
        public IActionResult DeleteEvaluation(int id)
        {
            EM.ChangeEvaluation(id);
         var result = EM.GetByIdSEvaluation(id);
            return Redirect("/Evaluation/Index/"+ result.StudentID);
        }

        [HttpGet]
        public IActionResult GetUpdate(int id)
        {
            var result1 = EM.EvaluationChooseList();
            ViewBag.Values = result1;
            var result = EM.GetByIdSEvaluation(id);
            return View("GetUpdate", result);
        }

        [HttpPost]
        public IActionResult UpdateEvaluation(Evaluation evaluation, int id)
        {
            EM.UpdateEvaluation(evaluation,id);
            return Redirect("/Evaluation/Index/" + evaluation.StudentID);
        }




    }
}

CorseUILayer/Views/Evaluation/GetEvaluation.cshtml
@model CorseEntity.Concrete.Evaluation
@{
    ViewData["Title"] = "GetEvaluation";
    Layout = "~/Views/Shared/_Layout_Corse.cshtml";
}

@using (Html.BeginForm("GetAddEvaluation", "Evaluation", FormMethod.Post))
{
    <br />

    <b>Idsi</b>
    @Html.TextBoxFor(x => x.EvaluationId, new { @class = "form-control" })

    <br />
    <b>Qiymeti</b>
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })

    <br />
    <b>Davamiyyeti</b>
    @Html.TextBoxFor(x => x.Continuity, new { @class = "form-control" })

   @* <br />
    <b>Tarix</b>
    @Html.TextBoxFor(x => x.PriceGiveDate, new { @class = "form-control" })
*@
    <br />
    <b>Telebe adi</b>
    @Html.DropDownListFor(x=>x.StudentID,(List<SelectListItem>)ViewBag.Values,new {@class="form-control"})

   
    <br />
    <button class="btn btn-info"> Qiymet ver </button>

}

CorseUILayer/Views/Evaluation/GetUpdate.cshtml
@model CorseEntity.Concrete.Evaluation
@{
    ViewData["Title"] = "GetUpdate";
    Layout = "~/Views/Shared/_Layout_Corse.cshtml";
}

@using (Html.BeginForm("UpdateEvaluation", "Evaluation", FormMethod.Post))
{
    <br />

    <b>Idsi</b>
    @Html.TextBoxFor(x => x.EvaluationId, new { @class = "form-control" })

    <br />
    <b>Qiymeti</b>
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })

    <br />
    <b>Davamiyyeti</b>
    @Html.TextBoxFor(x => x.Continuity, new { @class = "form-control" })
@*
    <br />
    <b>Tarix</b>
    @Html.TextBoxFor(x => x.PriceGiveDate, new { @class = "form-control" })
*@
    <br />
    <b>Telebe adi</b>
    @Html.DropDownListFor(x=>x.StudentID,(List<SelectListItem>)ViewBag.Values,new {@class="form-control"})

    
    <br />
    <button class="btn btn-info"> Guncelle </button>

}

CorseUILayer/Views/Evaluation/Index.cshtml
@model List<CorseEntity.Concrete.Evaluation>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout_Corse.cshtml";
}

<a href="/Evaluation/GetEvaluation/" class="btn btn-info">Yeni qiymet</a>
   


<br />
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Davamiyyeti</th>
        <th>Qiymeti</th>
        <th>Dersin tarixi</th>
        <th>Telebenin adi</th>
        <th>Guncelle</th>
        <th>Sil</th>
    </tr>
  
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.EvaluationId</td>
            <td>@item.Continuity</td>
            <td>@item.Price</td>
            <td>@item.PriceGiveDate.ToString("dd/MM/yyyy")</td>
          @*  <td>@item.StudentID</td>*@
            <td>@(ViewBag.StudentName.Count > 0 ? ViewBag.StudentName[0] : "Not Available")</td>
            <td><a href="/Evaluation/GetUpdate/@item.EvaluationId/" class="btn btn-warning">Guncelle</a></td>
            <td><a href="/Evaluation/DeleteEvaluation/@item.EvaluationId/" class="btn btn-danger">Sil</a></td>
           
        </tr>
       
    }

</table>